### ISSUE TITLE
Xcode build error due to AppLovinSDKResources.bundle

### ISSUE THREAD

**Issue by kkarunakaran** [AppLovin/Unity-Plugin-Demo#12]
@thomasmso  with Xcode New Build System. 

<img width="536" alt="image" src="https://user-images.githubusercontent.com/57362013/85058283-dcac7f80-b16f-11ea-8478-d5767008375c.png">

Multiple commands produce 'MCI/DerivedData/Unity-iPhone/Build/Products/ReleaseForRunning-iphoneos/MCI.app/Info.plist':
1) Target 'Unity-iPhone' (project 'Unity-iPhone') has copy command from 'MCI/AppLovin/AppLovinSDKResources.bundle/Info.plist' to 'MCI/DerivedData/Unity-iPhone/Build/Products/ReleaseForRunning-iphoneos/MCI.app/Info.plist'
2) Target 'Unity-iPhone' (project 'Unity-iPhone') has process command with output 'MCI/DerivedData/Unity-iPhone/Build/Products/ReleaseForRunning-iphoneos/MCI.app/Info.plist'

Cause.by
Unity-Plugin-Demo/Unity Plugin Demo/Assets/AppLovinSdk/Plugins/iOS/AppLovinSDKResources.bundle/

**Comment by thomasmso** [comment]
Hi @kkarunakaran - Are you able to send me the generated Xcode project to debug with? thomas.so@applovin.com

**Comment by kkarunakaran** [comment]
@thomasmso sure thing. Just wanted to confirm if AppLovinSDKResources.bundle is suppose to be in the iOS build?

**Comment by thomasmso** [comment]
Yes it is - it contains various resources our iOS SDK requires.

**Comment by kkarunakaran** [comment]
@thomasmso  thanks for your help on this. AppLovinSDKResources.bundle was marked as Standalone/Editor in the import settings out of box. While trying to include in Xcode project I was adding the info.plist inside the bundle to Copy Bundle Phase. With New Xcode Build System we can't have multiple .plist in Copy Bundle Phase. You were super responsive.

**Comment by thomasmso** [comment]
@kkarunakaran - Thanks for noting that, we'll ensure that it is marked for the iOS target only out of the box.
