### ISSUE TITLE
There is no reward for watching all paid videos

### ISSUE THREAD

**Issue by MaxFps** [AppLovin/Unity-Plugin-Demo#13]
I use Unity 2018.4.22, I have it installed in my Applovin, "Currency Name" and "Reward Amount per video watched", but why I only get the result returned "HIDDENREWARDED", can anyone help me? is not ?

**Comment by thomasmso** [comment]
Hi, please check out our [documentation](https://dash.applovin.com/docs/integration#iosUnityRewardedVideos) for rewarded videos.
