### ISSUE TITLE
No visible @interface for 'ALInterstitialAd' declares the selector 'showOver:andRender:'

### ISSUE THREAD

**Issue by hlongvu** [AppLovin/Unity-Plugin-Demo#14]
I got this error when building in Xcode 11.3.1. Can you help?
No visible @interface for 'ALInterstitialAd' declares the selector 'showOver:andRender:'

**Comment by thomasmso** [comment]
Thanks for reporting this issue @hlongvu - please see https://github.com/AppLovin/Unity-Plugin-Demo/issues/11
