### ISSUE TITLE
Banner display only six times

### ISSUE THREAD

**Issue by fjqingyou** [AppLovin/Unity-Plugin-Demo#5]
Add a Test Button , this function is Hide Banner
Banner Show -> Hide -> Show loop ,
Six or more times 
API Event LOADFAILED and LOADBANNERFAILED , but Banner displyed.

**Comment by thomasmso** [comment]
To clarify, you're saying that when you get `LOADBANNERFAILED` then call `HideAd()` the banner still displays? Otherwise, it should be fine, the banner is simply displaying the last ad that successfully loaded.

**Comment by thomasmso** [comment]
Closing this issue as no response has been received.
