### ISSUE TITLE
Correction at "Check if user replaced the SDK key"

### ISSUE THREAD

**Issue by tashfiq103** [AppLovin/Unity-Plugin-Demo#8]
`
// Check if user replaced the SDK key
		if (!"YOUR_SDK_KEY".Equals (SDK_KEY)) {
			StatusText.text = "ERROR: PLEASE UPDATE YOUR SDK KEY IN Assets/MainMenu.cs";
		} else {
			// Set SDK key and initialize SDK
			AppLovin.SetSdkKey (SDK_KEY);
			AppLovin.InitializeSdk ();
			AppLovin.SetTestAdsEnabled ("true");
			AppLovin.SetUnityAdListener ("MainMenu");
			AppLovin.SetRewardedVideoUsername ("demo_user");
		}
`

I think it should be "!"YOUR_SDK_KEY".Equal(SDK_KEY)" on the validation checking of sdk.

**Comment by thomasmso** [comment]
It is fine as is. We're checking if the user of this app actually replaced the SDK key placeholder value [here](https://github.com/AppLovin/Unity-Plugin-Demo/blob/master/Unity%20Plugin%20Demo/Assets/MainMenu.cs#L17) or not. If not, we'll prompt the error.

**Comment by tashfiq103** [comment]
Yes I believe I understand it's purpose, but when I even replaced it with the "SDK_KEY" with mine, it was still showing the error text prompt as it was still returning "**true**".

Sorry if I am still mistaking, just wanted to share the small issue. My sincere apologies If it's a mistake from my side :)

**Comment by thomasmso** [comment]
I just checked it and it works as expected for me, so I'd double-check your integration. Please feel to send an email to support@applovin.com if more issues arise. Thanks!
