### ISSUE TITLE
Not able to view any ads (not event test ads) on iPhone X (iOS 12.3.1)

### ISSUE THREAD

**Issue by oct-test** [AppLovin/Unity-Plugin-Demo#9]
I am trying to run this demo project on iPhone X and it is continuously receiving these errors: LOADINTERFAILED, LOADREWARDEDFAILED, LOADBANNERFAILED.

I tested the same build on iPhone 6s and iPad Mini. The build is running fine on these devices and ads are visible.

The iPhone X is present at different geo location than the iPhone 6s and iPad mini.

**Comment by oct-test** [comment]
This issue was happening due to an ad blocker app installed on one of my external testers.

**Comment by thomasmso** [comment]
@oct-test - Do you mind sharing what's the ad blocker app you used?. Feel free to email me directly at thomas.so@applovin.com if you prefer to use that communication channel instead.
